# Generated by Django 4.1.6 on 2024-06-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('name', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=10)),
                ('num_people', models.IntegerField()),
            ],
        ),
    ]
