# Generated by Django 4.1.6 on 2024-06-22 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnquiryForm',
        ),
    ]
